name: side-project-deployment

on:
 push:
   branches:
     - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debug Secrets
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" | sed 's/./& /g'
          echo "DOCKER_KEY=${{ secrets.DOCKER_TOKEN_KEY}}" | sed 's/./& /g'

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build with Gradle
        run: |
          ./gradlew clean build

      - name: Build and Push Docker image
        run: |
          sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN_KEY }}
          sudo docker build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/side1 .
          sudo docker tag ${{ secrets.DOCKER_USERNAME }}/side1 ${{ secrets.DOCKER_USERNAME }}/side1:v14
          sudo docker push ${{ secrets.DOCKER_USERNAME }}/side1:v14

  deploy:
      runs-on: ubuntu-22.04
      needs: build

      steps:
        - name: SSH to EC2 and Deploy
          uses: appleboy/ssh-action@v0.1.6
          with:
            host: ${{ secrets.EC2_IP }}
            username: ubuntu
            key: ${{ secrets.EC2_KEY }}
            port: 22
            script: |
              cd /home/ubuntu/side1  # 프로젝트 폴더로 이동
              sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN_KEY }}
              sudo docker compose down
              sudo docker pull ${{ secrets.DOCKER_USERNAME }}/side:v14
              sudo docker compose up -d --build
              
      
